"""add timer support to learning sets

Revision ID: 6accffb54c14
Revises: 8a7fd3092960
Create Date: 2025-08-04 00:26:00.492486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6accffb54c14'
down_revision: Union[str, None] = '8a7fd3092960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_difficulties')
    op.drop_table('review_sessions')
    op.drop_table('user_learning_set_items')
    op.drop_table('user_streaks')
    op.drop_table('leaderboard_scores')
    op.drop_table('badge_definitions')
    op.drop_table('user_element_reviews')
    op.drop_table('dataset_progress')
    op.drop_table('weekly_goals')
    op.drop_table('user_stats')
    op.drop_table('study_sessions')
    op.drop_index('ix_system_configs_id', table_name='system_configs')
    op.drop_index('ix_system_configs_key', table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_table('user_achievements')
    op.drop_table('optimal_schedules')
    op.drop_table('spaced_repetition_configs')
    op.drop_table('user_learning_sets')
    op.drop_table('user_field_attempts')
    op.drop_table('learning_insights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_insights',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('insight_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_points', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_actionable', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='learning_insights_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_insights_pkey')
    )
    op.create_table('user_field_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('element_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_field', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('answer_field', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('attempted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name='user_field_attempts_element_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_field_attempts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_field_attempts_pkey')
    )
    op.create_table('user_learning_sets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_paused', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('chunk_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_dataset_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='user_learning_sets_dataset_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_learning_sets_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_learning_sets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spaced_repetition_configs',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('algorithm', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('initial_ease', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('minimum_ease', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_ease', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ease_bonus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ease_penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('initial_interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('graduation_interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maximum_interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('learning_steps', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('relearning_steps', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='spaced_repetition_configs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='spaced_repetition_configs_pkey')
    )
    op.create_table('optimal_schedules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_retention', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('daily_review_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_study_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('next_7_days_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_30_days_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('optimal_session_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='optimal_schedules_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='optimal_schedules_pkey')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('achievement_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('achievement_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('badge_emoji', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_awarded', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_achievements_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_achievements_pkey'),
    sa.UniqueConstraint('user_id', 'achievement_title', name='_user_achievement_uc')
    )
    op.create_table('system_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_configs_pkey')
    )
    op.create_index('ix_system_configs_key', 'system_configs', ['key'], unique=False)
    op.create_index('ix_system_configs_id', 'system_configs', ['id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cards_studied', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_correct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_new', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_due', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('accuracy_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('improvement_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('time_of_day', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='study_sessions_dataset_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='study_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='study_sessions_pkey')
    )
    op.create_table('user_stats',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_elements_seen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_elements_mastered', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_study_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overall_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_datasets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_datasets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_session_length_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sessions_this_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sessions_this_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mastery_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('learning_velocity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('retention_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_stats_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='user_stats_pkey')
    )
    op.create_table('weekly_goals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_sessions_per_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_minutes_per_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_cards_per_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('week_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sessions_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minutes_studied', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_studied', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal_achieved', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('streak_weeks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='weekly_goals_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='weekly_goals_pkey')
    )
    op.create_table('dataset_progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('elements_in_dataset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('elements_seen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('elements_mastered', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_stage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accuracy_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_study_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('completion_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_studied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='dataset_progress_dataset_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='dataset_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dataset_progress_pkey'),
    sa.UniqueConstraint('user_id', 'dataset_id', name='uq_dataset_progress_user_dataset')
    )
    op.create_table('user_element_reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('element_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('success_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_reviewed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_due', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('interval_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ease_factor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_difficult', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name='user_element_reviews_element_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_element_reviews_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_element_reviews_pkey')
    )
    op.create_table('badge_definitions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('criteria_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('criteria_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='badge_definitions_pkey'),
    sa.UniqueConstraint('name', name='badge_definitions_name_key')
    )
    op.create_table('leaderboard_scores',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('score_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='leaderboard_scores_dataset_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='leaderboard_scores_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='leaderboard_scores_pkey'),
    sa.UniqueConstraint('user_id', 'score_type', 'dataset_id', 'period', name='_user_score_uc')
    )
    op.create_table('user_streaks',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_activity', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('streak_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_streaks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='user_streaks_pkey')
    )
    op.create_table('user_learning_set_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('learning_set_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('element_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name='user_learning_set_items_element_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_set_id'], ['user_learning_sets.id'], name='user_learning_set_items_learning_set_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_learning_set_items_pkey')
    )
    op.create_table('review_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cards_reviewed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_correct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='review_sessions_dataset_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='review_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='review_sessions_pkey')
    )
    op.create_table('card_difficulties',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('element_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('average_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('learning_velocity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('retention_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_calculated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name='card_difficulties_element_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='card_difficulties_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='card_difficulties_pkey'),
    sa.UniqueConstraint('user_id', 'element_id', name='uq_card_difficulty_user_element')
    )
    # ### end Alembic commands ###
